WKTON -> WCKTON

diff --git a/bin/deploy/1-deploy-tkn b/bin/deploy/1-deploy-tkn
--- a/bin/deploy/1-deploy-tkn
+++ b/bin/deploy/1-deploy-tkn
@@ -4,29 +4,29 @@ set -e
 
 . $(PWD)/bin/init
 
-tokens=("GOLD" "WOOD" "HHO" "FIRE" "SIOO")
+# tokens=("GOLD" "WOOD" "HHO" "FIRE" "SIOO")
 
-for token in "${tokens[@]}"; do
-    address=$(dapp create $token)
-    setting=$token
-    if [[ "$setting" = "HHO" ]]; then
-	setting="WATER"
-    fi
-    if [[ "$setting" = "SIOO" ]]; then
-	setting="SOIL"
-    fi
-    addAddress "TOKEN_ERC20_$setting" "$address"
-    id="CONTRACT_${setting}_ERC20_TOKEN"
-    echo $id
-    id=$(seth --to-bytes32 $(seth --to-hex $(seth --from-ascii $id)))
-    echo $id
-    seth send $SETTINGSREGISTRY "setAddressProperty(bytes32,address)" $id $address 
-    if test $(seth call $SETTINGSREGISTRY "addressOf(bytes32)(address)" $id) != $address; then
-      (echo "check register ${registry} failed."; exit 1;)
-    fi
-done
+# for token in "${tokens[@]}"; do
+#     address=$(dapp create $token)
+#     setting=$token
+#     if [[ "$setting" = "HHO" ]]; then
+# 	setting="WATER"
+#     fi
+#     if [[ "$setting" = "SIOO" ]]; then
+# 	setting="SOIL"
+#     fi
+#     addAddress "TOKEN_ERC20_$setting" "$address"
+#     id="CONTRACT_${setting}_ERC20_TOKEN"
+#     echo $id
+#     id=$(seth --to-bytes32 $(seth --to-hex $(seth --from-ascii $id)))
+#     echo $id
+#     seth send $SETTINGSREGISTRY "setAddressProperty(bytes32,address)" $id $address 
+#     if test $(seth call $SETTINGSREGISTRY "addressOf(bytes32)(address)" $id) != $address; then
+#       (echo "check register ${registry} failed."; exit 1;)
+#     fi
+# done
 
-ring=$(dapp create WRING)
+ring=$(dapp create WCRING)
 addAddress "TOKEN_ERC20_RING" $ring
 id=$(seth --to-bytes32 $(seth --from-ascii "CONTRACT_RING_ERC20_TOKEN"))
 echo $id
@@ -35,7 +35,7 @@ if test $(seth call $SETTINGSREGISTRY "addressOf(bytes32)(address)" $id) != $rin
   (echo "check register ${registry} failed."; exit 1;)
 fi
 
-kton=$(dapp create WKTON)
+kton=$(dapp create WCKTON)
 addAddress "TOKEN_ERC20_KTON" $kton
 id=$(seth --to-bytes32 $(seth --from-ascii "CONTRACT_KTON_ERC20_TOKEN"))
 echo $id
