crab: deploy gov

diff --git a/bin/deploy/11-deploy-gov b/bin/deploy/11-deploy-gov
--- a/bin/deploy/11-deploy-gov
+++ b/bin/deploy/11-deploy-gov
@@ -8,7 +8,7 @@ sig="initialize(address,address,address)"
 SNAPSHOT_PROXY=$(deployProxy2 governance contracts/SnapshotProxy.sol:SnapshotProxy contracts/EvolutionTeller.sol:EvolutionTeller "$sig" "$SETTINGSREGISTRY" "$TOKEN_ERC20_KTON" "$TOKEN_ERC20_RING")
 # register "addr" "CONTRACT_DIVIDENDS_POOL" "$SNAPSHOT_PROXY"
 
-seth send $SNAPSHOT_PROXY "addRewardDistribution(address)" $REVENUEPOOL_PROXY
-if test "$(seth call $SNAPSHOT_PROXY "rewardDistributions(address)(bool)" $REVENUEPOOL_PROXY)" != true; then
-  (echo "addRewardDistribution failed!"; exit 1)
-fi
+# seth send $SNAPSHOT_PROXY "addRewardDistribution(address)" $REVENUEPOOL_PROXY
+# if test "$(seth call $SNAPSHOT_PROXY "rewardDistributions(address)(bool)" $REVENUEPOOL_PROXY)" != true; then
+#   (echo "addRewardDistribution failed!"; exit 1)
+# fi
