deploy and registey opt

diff --git a/bin/deploy/11-deploy-gov b/bin/deploy/11-deploy-gov
--- a/bin/deploy/11-deploy-gov
+++ b/bin/deploy/11-deploy-gov
@@ -4,17 +4,11 @@ set -e
 
 . $(PWD)/bin/init
 
-EVOLUTIONTELLER=$(dappCreate governance contracts/EvolutionTeller.sol:EvolutionTeller)
-
-calldata=$(seth calldata "initialize(address,address,address)" $SETTINGSREGISTRY $TOKEN_ERC20_KTON $TOKEN_ERC20_RING)
-SNAPSHOT_PROXY=$(dappCreate governance contracts/SnapshotProxy.sol:SnapshotProxy $EVOLUTIONTELLER $FURNACEPROXYADMIN $calldata)
-
-diviendsId=$(seth --to-bytes32 $(seth --to-hex $(seth --from-ascii "CONTRACT_DIVIDENDS_POOL")))
-seth send $SETTINGSREGISTRY "setAddressProperty(bytes32,address)" $diviendsId $SNAPSHOT_PROXY
-if test $(seth call $SETTINGSREGISTRY "addressOf(bytes32)(address)" $diviendsId) != $SNAPSHOT_PROXY; then
-  (echo "check register ${registry} failed."; exit 1;)
-fi
+sig="initialize(address,address,address)"
+SNAPSHOT_PROXY=$(deployProxy governance contracts/SnapshotProxy.sol:SnapshotProxy contracts/EvolutionTeller.sol:EvolutionTeller "$sig" "$SETTINGSREGISTRY" "$TOKEN_ERC20_KTON" "$TOKEN_ERC20_RING")
+register "addr" "CONTRACT_DIVIDENDS_POOL" "$SNAPSHOT_PROXY"
 
 seth send $SNAPSHOT_PROXY "addRewardDistribution(address)" $REVENUEPOOL_PROXY
-
-seth call $SNAPSHOT_PROXY "rewardDistributions(address)" $REVENUEPOOL_PROXY
+if test "$(seth call $SNAPSHOT_PROXY "rewardDistributions(address)(bool)" $REVENUEPOOL_PROXY)" != true; then
+  (echo "addRewardDistribution failed!"; exit 1)
+fi
diff --git a/bin/init b/bin/init
--- a/bin/init
+++ b/bin/init
@@ -77,31 +77,91 @@ if [[ "$DEPLOY_CHAIN?" ]]; then
   esac
 fi
 
+
+deployProxy() {
+  set -e
+  local lib; lib=$1
+  local proxy; proxy=$2
+  local class; class=$3
+  local sig; sig=$4
+  local calldata; calldata=$(seth calldata "$sig" ${@:5})
+  local addr; addr=$(dappCreate "$lib" "$class")
+  local proxyAddr; proxyAddr=$(dappProxy "$proxy" "$addr" "${EVOPROXYADMIN?}" "$calldata")
+  echo "$proxyAddr"
+}
+
+
 dappCreate() {
-    set -e
-    local lib; lib=$1
-    local class; class=$2
-    local addr; addr=$(DAPP_OUT="$DAPP_LIB/$lib/out" dapp create "$class" "${@:3}")
-    local name; name=${class#*:}
-    local proxy; proxy=$(toUpper "$name")
-    if test "${proxy%%"PROXY"}" == "PROXY"; then 
-      proxy="${proxy%%"PROXY"}_PROXY"
-    fi
-    addAddress "$proxy" "$addr" >/dev/null
-    echo "$addr"
+  set -e
+  local lib; lib=$1
+  local class; class=$2
+  local addr; addr=$(DAPP_OUT="$DAPP_LIB/$lib/out" dapp create "$class" "${@:3}")
+  local name; name=${class#*:}
+  local proxy; proxy=$(toUpper "$name")
+  if test "${proxy%%"PROXY"}" == "PROXY"; then 
+    proxy="${proxy%%"PROXY"}_PROXY"
+  fi
+  addAddress "$proxy" "$addr" >/dev/null
+  info "$proxy deployed at $addr"
+  echo "$addr"
 }
 
 dappProxy() {
-    set -e
-    local class; class=$1
-    local addr; addr=$(DAPP_OUT="./out" dapp create "$class" "${@:2}")
-    local name; name=${class#*:}
-    local proxy; proxy=$(toUpper "$name")
-    if test "${proxy%%"PROXY"}" == "PROXY"; then 
-      proxy="${proxy%%"PROXY"}_PROXY"
-    fi
-    echo "$addr"
+  set -e
+  local class; class=$1
+  local addr; addr=$(DAPP_OUT="./out" dapp create "$class" "${@:2}")
+  local name; name=${class#*:}
+  local proxy; proxy=$(toUpper "$name")
+  if test "${proxy%%"PROXY"}" == "PROXY"; then 
+    proxy="${proxy%%"PROXY"}_PROXY"
+  fi
+  info "$proxy deployed at $addr"
+  echo "$addr"
 }
+
+addressOf() {
+  local id=$(seth --to-bytes32 $(seth --from-ascii "${1?}"))
+  local addr=$(seth call "$SETTINGSREGISTRY" "addressOf(bytes32)(address)" "$id")
+  echo "$(seth --to-checksum-address $addr)"
+}
+
+setAddress() {
+  local id=$(seth --to-bytes32 $(seth --from-ascii "${1?}"))
+  local addr="${2?}"
+  seth send "${SETTINGSREGISTRY?}" "setAddressProperty(bytes32,address)" "$id" "$addr" 
+  if test "$addr" != "$(addressOf $1)"; then 
+    (echo "registry $1 failed!"; exit 1;)
+  fi
+  info "$1 regisered."
+}
+
+uintOf() {
+  local id=$(seth --to-bytes32 $(seth --from-ascii "${1?}"))
+  echo "$(seth call "$SETTINGSREGISTRY" "uintOf(bytes32)(uint256)" "$id")"
+}
+
+setUint() {
+  set -ex
+  local id=$(seth --to-bytes32 $(seth --from-ascii "${1?}"))
+  local addr="${2?}"
+  seth send "${SETTINGSREGISTRY?}" "setUintProperty(bytes32,uint256)" "$id" "$addr" 
+  if test "$addr" != "$(uintOf $1)"; then 
+    (echo "registry $1 failed!"; exit 1;)
+  fi
+  info "$1 regisered."
+}
+
+register() {
+  local t; t="$1"
+  if test "$t" == "addr"; then
+    setAddress "${@:2}"
+  elif test "$t" == "uint"; then
+    setUint "${@:2}"
+  else
+    (echo "registry $2 failed!"; exit 1;)
+  fi
+}
+
 
 loadConf() {
   if [ -z "$1" ]  
