land owner have right to stop mining

diff --git a/bin/migrate/0-migrate-lnd b/bin/migrate/0-migrate-lnd
--- a/bin/migrate/0-migrate-lnd
+++ b/bin/migrate/0-migrate-lnd
@@ -5,19 +5,19 @@ set -e
 . $(PWD)/bin/init
 
 # ropsten
-lib="land"
-LANDRESOURCEV6=$(dappCreate "$lib" contracts/LandResourceV6.sol:LandResourceV6)
-seth send -F $OWNER  $LANDRESOURCE_PROXY "upgradeTo(address)" $LANDRESOURCEV6
-if test $(seth call $LANDRESOURCE_PROXY "implementation()(address)") != $LANDRESOURCEV6; then
-  (echo "check migration failed."; exit 1;)
-fi
-echo >&2 "${0##*/}: info: migration finished." 
-
-# heco
 # lib="land"
 # LANDRESOURCEV6=$(dappCreate "$lib" contracts/LandResourceV6.sol:LandResourceV6)
-# seth send $EVOPROXYADMIN "upgrade(address,address)" $LANDRESOURCE_PROXY $LANDRESOURCEV6
-# if test $(seth call $EVOPROXYADMIN "getProxyImplementation(address)(address)" $LANDRESOURCE_PROXY) != $LANDRESOURCEV6; then
+# seth send -F $OWNER  $LANDRESOURCE_PROXY "upgradeTo(address)" $LANDRESOURCEV6
+# if test $(seth call $LANDRESOURCE_PROXY "implementation()(address)") != $LANDRESOURCEV6; then
 #   (echo "check migration failed."; exit 1;)
 # fi
 # echo >&2 "${0##*/}: info: migration finished." 
+
+# heco
+lib="land"
+LANDRESOURCEV6=$(dappCreate "$lib" contracts/LandResourceV6.sol:LandResourceV6)
+seth send $EVOPROXYADMIN "upgrade(address,address)" $LANDRESOURCE_PROXY $LANDRESOURCEV6
+if test $(seth call $EVOPROXYADMIN "getProxyImplementation(address)(address)" $LANDRESOURCE_PROXY) != $LANDRESOURCEV6; then
+  (echo "check migration failed."; exit 1;)
+fi
+echo >&2 "${0##*/}: info: migration finished." 
