fix auth and add mutilsig

diff --git a/bin/migrate/0-migrate-lnd b/bin/migrate/0-migrate-lnd
--- a/bin/migrate/0-migrate-lnd
+++ b/bin/migrate/0-migrate-lnd
@@ -4,11 +4,19 @@ set -e
 
 . $(PWD)/bin/init
 
-LANDBASE=$(dapp create LandBase)
-echo >&2 "${0##*/}: info: LandBase created."
-seth send $LANDBASE_PROXY "upgradeTo(address)" $LANDBASE
-if test $(seth call $LANDBASE_PROXY "implementation()(address)") != $LANDBASE; then
+# LANDBASE=$(dapp create LandBase)
+# echo >&2 "${0##*/}: info: LandBase created."
+# seth send $LANDBASE_PROXY "upgradeTo(address)" $LANDBASE
+# if test $(seth call $LANDBASE_PROXY "implementation()(address)") != $LANDBASE; then
+#   (echo "check migration failed."; exit 1;)
+# fi
+# addAddress "LANDBASE" "$LANDBASE"
+# echo >&2 "${0##*/}: info: migration finished." 
+
+lib="land"
+LANDRESOURCEV6=$(dappCreate "$lib" contracts/LandResourceV6.sol:LandResourceV6)
+seth send $EVOPROXYADMIN "upgrade(address,address)" $LANDRESOURCE_PROXY $LANDRESOURCEV6
+if test $(seth call $EVOPROXYADMIN "getProxyImplementation(address)(address)" $LANDRESOURCE_PROXY) != $LANDRESOURCEV6; then
   (echo "check migration failed."; exit 1;)
 fi
-addAddress "LANDBASE" "$LANDBASE"
 echo >&2 "${0##*/}: info: migration finished." 
