fix typo

diff --git a/bin/migrate/2-migrate-apo b/bin/migrate/2-migrate-apo
--- a/bin/migrate/2-migrate-apo
+++ b/bin/migrate/2-migrate-apo
@@ -6,15 +6,15 @@ set -e
 
 lib="apostle"
 # ropsten
-APOSTLEBASEV4=$(dappCreate "$lib" contracts/ApostleBaseV4.sol:ApostleBaseV4)
-seth send -F $OWNER  $APOSTLEBASE_PROXY "upgradeTo(address)" $APOSTLEBASEV4
-if test $(seth call $APOSTLEBASE_PROXY "implementation()(address)") != $APOSTLEBASEV4; then
-  (echo "check migration failed."; exit 1;)
-fi
-echo >&2 "${0##*/}: info: migration finished." 
+# APOSTLEBASEV4=$(dappCreate "$lib" contracts/ApostleBaseV4.sol:ApostleBaseV4)
+# seth send -F $OWNER  $APOSTLEBASE_PROXY "upgradeTo(address)" $APOSTLEBASEV4
+# if test $(seth call $APOSTLEBASE_PROXY "implementation()(address)") != $APOSTLEBASEV4; then
+#   (echo "check migration failed."; exit 1;)
+# fi
+# echo >&2 "${0##*/}: info: migration finished." 
 
 # heco
-# dappUpgrade "$lib" contracts/ApostleBaseV4.sol:ApostleBaseV4 "$APOSTLEBASE_PROXY"
+dappUpgrade "$lib" contracts/ApostleBaseV4.sol:ApostleBaseV4 "$APOSTLEBASE_PROXY"
 
 # dappUpgrade "$lib" contracts/ApostleClockAuctionV2.sol:ApostleClockAuctionV2 "$APOSTLECLOCKAUCTION_PROXY"
 
