pet: forward compatible

diff --git a/bin/migrate/6-migrate-pet b/bin/migrate/6-migrate-pet
--- a/bin/migrate/6-migrate-pet
+++ b/bin/migrate/6-migrate-pet
@@ -5,6 +5,15 @@ set -e
 . $(PWD)/bin/init
 
 # ERC721Adaptor
-seth send $INTERSTELLARENCODERV3 -F $OWNER "registerNewOwnershipContract(address,uint8)" $CK $(seth --to-hex 2) 
-seth send $ERC721BRIDGE_PROXY -F $OWNER "registerAdaptor(address,address)" $CK $ERC721ADAPTOR_PROXY
-info "CK registry finished."
+# seth send $INTERSTELLARENCODERV3 -F $OWNER "registerNewOwnershipContract(address,uint8)" $CK $(seth --to-hex 2) 
+# seth send $ERC721BRIDGE_PROXY -F $OWNER "registerAdaptor(address,address)" $CK $ERC721ADAPTOR_PROXY
+# info "CK registry finished."
+
+lib="common-contracts"
+ERC721ADAPTOR=$(dappCreate "$lib" contracts/ERC721Adaptor.sol:ERC721Adaptor)
+seth send -F $OWNER $ERC721ADAPTOR_PROXY "upgradeTo(address)" $ERC721ADAPTOR
+if test $(seth call $ERC721ADAPTOR_PROXY "implementation()(address)") != $ERC721ADAPTOR; then
+  (echo "check migration failed."; exit 1;)
+fi
+
+seth send -F $OWNER $ERC721ADAPTOR_PROXY "changeOrininNft(address)" $CK 
diff --git a/bin/test/4-test-pet b/bin/test/4-test-pet
--- a/bin/test/4-test-pet
+++ b/bin/test/4-test-pet
@@ -4,14 +4,91 @@ set -e
 
 . $(PWD)/bin/init
 
-owner=0x0f14341A7f464320319025540E8Fe48Ad0fe5aec
-to=0xa1511E5C683A007056CAa1d9A8D6A37464826280
-gene=39
+p() { printf "%-7s %-20s\n" "$1" "$2"; }
 
-for i in {1..2}; do
-  seth send "$CK" "createPromoKitty(uint256,address)" "$(($gene+$i))" "$to"
-done
+# owner=0x0f14341A7f464320319025540E8Fe48Ad0fe5aec
+# to=0xa1511E5C683A007056CAa1d9A8D6A37464826280
+# gene=39
+
+# for i in {1..2}; do
+#   seth send "$CK" "createPromoKitty(uint256,address)" "$(($gene+$i))" "$to"
+# done
 
 # for i in {1..2}; do
 #   seth send -F "$owner" "$CK" "transfer(address,uint256)" "$to" "$(($gene+$i))" 
 # done
+
+# tie old ck pet
+apostle1=0x2a010001010001020000000000000001000000000000000000000000000000a4
+strength () {
+  land=0x2a0100010100010100000000000000010000000000000000000000000000011e
+  resource=0xC5C0f115C05dd10625A5d4d0fAf284100AD56E68
+  evo apo-bas strength $apostle1 $resource $land --chain ropsten
+}
+
+# seth send $CK "createPromoKitty(uint256,address)" 1 $AUTH
+# ckpet=$(seth call $CK "totalSupply()(uint256)")
+# echo $ckpet
+ckpet=51
+
+mirrorTokenId=0x2a01000101000203800000000000010000000000000000000000000000000033
+# 2a01000101000203800000000000010000000000000000000000000000000035
+# p "Before" $(strength)
+# seth estimate $PETBASE_PROXY "bridgeInAndTie(address,uint256,uint256)" $CK $ckpet $apostle1
+# seth send $PETBASE_PROXY "bridgeInAndTie(address,uint256,uint256)" $CK $ckpet $apostle1
+# p "Mid" $(strength)
+# seth send $PETBASE_PROXY "untiePetToken(uint256)" "$mirrorTokenId"
+# p "After" $(strength)
+
+# seth send $ERC721BRIDGE_PROXY "swapOut721(uint256)" $mirrorTokenId
+
+# # bridge in
+approved=$(seth call "$CK" "kittyIndexToApproved(uint256)(address)" "$ckpet")
+if test "$approved" != $(seth --to-checksum-address $ERC721BRIDGE_PROXY); then
+  seth send "$CK" "approve(address,uint256)" "$ERC721BRIDGE_PROXY" "$ckpet"
+fi
+
+tx=$(seth send --async "$ERC721BRIDGE_PROXY" "swapIn721(address,uint256)" "$CK" "$ckpet")
+echo "$tx"
+echo >&2 -n "${0##*/}: Waiting for transaction receipt..."
+block=$(SETH_TICK=true seth receipt "$tx" blockNumber)
+block=$(seth --to-hex "$block")
+echo >&2
+
+sig="SwapIn(address,uint256,uint256,address)"
+keccak=$(seth keccak "$(seth --from-ascii $sig)")
+logs=$(seth rpc eth_getLogs -- \
+  -n {} \
+    -s "${ERC721BRIDGE_PROXY?}" -i address \
+    -s "$block"                 -i fromBlock \
+    -s "$block"                 -i toBlock \
+  -n [] \
+    -s "$keccak" -i append \
+  -i topics \
+  -i append | echo "[$(paste -sd , -)]")
+data=$(echo "$logs" | jshon -a -e data -u)
+dec=$(seth --abi-decode "f()(address,uint256,bytes32,address)" "$data")
+mirrorTokenId=$(echo $dec | cut -d' ' -f 3)
+hash=$(echo "$logs" | jshon -a -e transactionHash -u)
+
+if [ "$hash" == "$tx" ]; then
+  echo "$tx"
+  p  "$mirrorTokenId"      "SwapIn"
+else
+  echo >&2 "${0##*/}: Transaction failed."
+  seth >&2 receipt "$tx"
+  exit 1
+fi
+
+# tie pet
+p "Before" "$(strength)" 
+
+seth send $PETBASE_PROXY "tiePetTokenToApostle(uint256,uint256)" "$mirrorTokenId" "$apostle1"
+p "Mid" "$(strength)" 
+
+seth send $PETBASE_PROXY "untiePetToken(uint256)" "$mirrorTokenId"
+p "After" "$(strength)" 
+
+## bridge out
+seth send $ERC721BRIDGE_PROXY "swapOut721(uint256)" $mirrorTokenId
+
diff --git a/bin/test/6-test-brige b/bin/test/6-test-brige
--- a/bin/test/6-test-brige
+++ b/bin/test/6-test-brige
@@ -4,33 +4,81 @@ set -e
 
 . $(PWD)/bin/init
 
+p() { printf "%-7s %-50s %-10s\n" "$1" "$2" "$3"; }
+
+# tos=(
+#   0x735182c782CB8e7806F8903dE7913e6880CbF82E
+#   0xf422673CB7a673f595852f7B00906408A0b073db
+#   0xa1511E5C683A007056CAa1d9A8D6A37464826280
+# )
+# for i in {1..20}; do
+#   seth send "$POLKAPET" "create(uint256,uint256,string,bytes)" 10000000 5 '""' 0x00 
+# done
+# for to in "${tos[@]}"; do
+#   seth send "$POLKAPET" "mint(address,uint256,uint256,bytes)" "$to" 2 5 "0x00"
+#   seth send "$POLKAPET" "mint(address,uint256,uint256,bytes)" "$to" 11 5 "0x00"
+#   seth send "$POLKAPET" "mint(address,uint256,uint256,bytes)" "$to" 20 5 "0x00"
+# done
+
 # bridge in
+id=11
+seth call "$POLKAPET" "balanceOf(address,uint256)(uint256)"  "$AUTH" "$id"
+approved=$(seth call "$POLKAPET" "isApprovedForAll(address,address)(bool)" "$AUTH" "$ERC721BRIDGE_PROXY")
+if test "$approved" == false; then
+  seth send "$POLKAPET" "setApprovalForAll(address,bool)" "$ERC721BRIDGE_PROXY" true 
+fi
 
 
-id=$(seth --to-uint256 2)
-value=$(seth --to-uint256 2)
-to=0xa1511E5C683A007056CAa1d9A8D6A37464826280
-# seth call "$POLKAPET" "balanceOf(address,uint256)" $AUTH $id
-seth call "$POLKAPET" "balanceOf(address,uint256)(uint256)"  $to $id
-# seth send "$POLKAPET" "safeTransferFrom(address,address,uint256,uint256,bytes)" "$AUTH" "$ERC721BRIDGE_PROXY" "$id" "$value" "0x00"
+tx=$(seth send --async "$ERC721BRIDGE_PROXY" "swapIn1155(address,uint256,uint256)" "$POLKAPET" "$id" 1)
+echo "$tx"
+echo >&2 -n "${0##*/}: Waiting for transaction receipt..."
+block=$(SETH_TICK=true seth receipt "$tx" blockNumber)
+block=$(seth --to-hex "$block")
+echo >&2
 
-seth send "$POLKAPET" "mint(address,uint256,uint256,bytes)" "$to" "$id" 5 "0x00"
+sig="SwapIn(address,uint256,uint256,address)"
+keccak=$(seth keccak "$(seth --from-ascii $sig)")
+logs=$(seth rpc eth_getLogs -- \
+  -n {} \
+    -s "${ERC721BRIDGE_PROXY?}" -i address \
+    -s "$block"                 -i fromBlock \
+    -s "$block"                 -i toBlock \
+  -n [] \
+    -s "$keccak" -i append \
+  -i topics \
+  -i append | echo "[$(paste -sd , -)]")
+data=$(echo "$logs" | jshon -a -e data -u)
+dec=$(seth --abi-decode "f()(address,uint256,bytes32,address)" "$data")
+mirrorTokenId=$(echo $dec | cut -d' ' -f 3)
+hash=$(echo "$logs" | jshon -a -e transactionHash -u)
 
-## bridge out
-
-# seth send $ERC721BRIDGE_PROXY "swapOut1155(uint256)" 0x2a0100010100050380000000000001030000000000000000000000000000006c
+if [ "$hash" == "$tx" ]; then
+  echo "$tx"
+  p "ERC721BRIDGE_PROXY"  "$mirrorTokenId"      "SwapIn"
+else
+  echo >&2 "${0##*/}: Transaction failed."
+  seth >&2 receipt "$tx"
+  exit 1
+fi
 
 # tie pet
-# apostle1=0x2a0100010100010200000000000000010000000000000000000000000000006b
-# ppet=0x2a0100010100050380000000000001030000000000000000000000000000006c
-# seth send $PETBASE_PROXY "tiePetTokenToApostle(uint256,uint256)" "$ppet" "$apostle1"
 
-# seth send $PETBASE_PROXY "untiePetToken(uint256)" "$ppet"
+apostle1=0x2a010001010001020000000000000001000000000000000000000000000000a4
+strength () {
+  land=0x2a0100010100010100000000000000010000000000000000000000000000011e
+  resource=0xC5C0f115C05dd10625A5d4d0fAf284100AD56E68
+  evo apo-bas strength $apostle1 $resource $land --chain ropsten
+}
 
-# tie ck pet
-# seth send $CK "createPromoKitty(uint256,address)" 1 $AUTH
-# ckpet=$(seth --to-uint256 3)
-# apostle1=0x2a03000103000102000000000000000300000000000000000000000000000021
-# seth estimate $PETBASE_PROXY "bridgeInAndTie(address,uint256,uint256)" $CK $ckpet $apostle1
-# seth send $PETBASE_PROXY "bridgeInAndTie(address,uint256,uint256)" $CK $ckpet $apostle1
+ppet=$mirrorTokenId
+p "Before" "$(strength)" "POLKAPET"
+
+seth send $PETBASE_PROXY "tiePetTokenToApostle(uint256,uint256)" "$ppet" "$apostle1"
+p "Mid" "$(strength)" "POLKAPET"
+
+seth send $PETBASE_PROXY "untiePetToken(uint256)" "$ppet"
+p "After" "$(strength)" "POLKAPET"
+
+## bridge out
+seth send $ERC721BRIDGE_PROXY "swapOut1155(uint256)" $ppet
 
